application: eecs-393-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /index\.html
  script: main.app
  login: required
- url: /request
  script: request.app
- url: /upload.*
  script: data.document.app
  login: required
- url: /other
  script: other.app
- url: /debug
  script: debug.app
- url: /add_assignment*
  script: data.courseitem.app 
- url: /bootstrap
  static_dir: bootstrap
- url: /script
  static_dir: web/JS
- url: /stylesheet
  static_dir: web/CSS
- url: /.*
  script: main.app
  login: required

libraries:
- name: ssl
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest
