application: eecs-393-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /other
  script: other.app
- url: /debug
  script: debug.app
- url: /bootstrap
  static_dir: bootstrap