application: eecs-393-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
  login: required
- url: /request
  script: request.app
- url: /upload.*
  script: document.app
  login: required
- url: /other
  script: other.app
>>>>>>> Stashed changes
- url: /debug
  script: debug.app
- url: /bootstrap
  static_dir: bootstrap
- url: /script
  static_dir: web/JS
- url: /stylesheet
  static_dir: web/CSS
